### PR TITLE
Handle myFT errors

### PR DESCRIPTION
**Pull request by ironsidevsquincy**
cc @laurieboyes

### CODE REVIEW

**Comment by laurieboyes** [comment]
👍  so it'll wait for the timeout limit then return an empty array?

**Comment by ironsidevsquincy** [comment]
Yeah. It's annoying `fetch` doesn't allow a timeout to be set

**Comment by laurieboyes** [comment]
Ah node-fetch does though! And you can now send an `options` param to myftClient.fetchJson (documenting this is on my todo list): https://github.com/Financial-Times/next-myft-client/blob/master/src/myft-api.js#L25

But yeah, that's just for info, this is fine

**Comment by ironsidevsquincy** [comment]
Ah, cool. What's a good timeout for those endpoints? 3 secs?

**Comment by laurieboyes** [comment]
Hm, we're still working that out. I've put it at 2 secs for email generation for now. 3 is fine.

**Pull request merged**
