### PR TITLE
Remove fastly logging, it's broken and causes Fastly issues

### PR DESCRIPTION
**Pull request by matthew-andrews**
@ironsidevsquincy

### CODE REVIEW

**Comment by ironsidevsquincy** [comment]
How is it broken? Logs are appearing in Splunk

**Comment by matthew-andrews** [comment]
oh really?

**Comment by matthew-andrews** [comment]
ah ok, yes this can be closed.

**Comment by matthew-andrews** [comment]
@ironsidevsquincy just heard back from Fastly — it's the graphql staging server causing problems!  I'll add ft-next-syslog-server to that VCL too to fix that

**Comment by ironsidevsquincy** [comment]
spoke to @phamann, said to not worry about staging (will confuse the logs)

if we want to do it, myft will probably need to update too

**Comment by matthew-andrews** [comment]
Fastly have asked either to add a log endpoint OR removing logging from our VCLs.  So if a service has logging it should have it in all environments :-/

**Comment by matthew-andrews** [comment]
And yes, I have a list of services from them I need to work through — MyFT is included

**Pull request closed without merging**
