### PR TITLE
Add ‘url’ to the schema

### PR DESCRIPTION
**Pull request by matthew-andrews**

### CODE REVIEW

**Comment by andygout** [comment]
How come? Will apps making GraphQL queries need to add `url` to requested values?

**Comment by matthew-andrews** [comment]
yup, rather than constructing their own `content/${uuid}` ones

**Comment by andygout** [comment]
Okay - only a few apps currently using GraphQL so shouldn't be too much to add.

👍

**Comment by matthew-andrews** [comment]
yup, i'm working through this slowly and carefully :)

**Pull request merged**
